opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build and archive the iOS app"
  lane :build_release do
    build_app(
      project: "App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      output_directory: "App/output",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.appgyver.i360" => "i360"
        }
      }
    )
  end

  desc "Build and upload to TestFlight"
  lane :deploy_apple do
    build_release
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
