name: Deploy to Firebase Hosting (preview)

on:
  push:
    branches:
      - vite

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
        env:
          VITE_BASEROW_KEY: ${{ secrets.VITE_BASEROW_KEY }}
          VITE_BASEROW_URL: ${{ secrets.VITE_BASEROW_URL }}
          VITE_BASEROW_TABLE_SCIENCES: ${{ secrets.VITE_BASEROW_TABLE_SCIENCES }}
          VITE_BASEROW_TABLE_RESOURCES: ${{ secrets.VITE_BASEROW_TABLE_RESOURCES }}
          VITE_BASEROW_TABLE_QURAN: ${{ secrets.VITE_BASEROW_TABLE_QURAN }}
          VITE_TRANSLATOR_KEY: ${{ secrets.VITE_TRANSLATOR_KEY }}
          VITE_TRANSLATOR_URL: ${{ secrets.VITE_TRANSLATOR_URL }}
          VITE_PSE_CX: ${{ secrets.VITE_PSE_CX }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_I360_E }}'
          channelId: pwa-test
          projectId: i360-e
